#
# Cntlm Authentication Proxy Configuration
#

Auth            NTLMv2
PassLM          2C75B2F2D1B9EF26578BF3269C8D88E5
PassNT          74A7DF9DA133D42421A6A9F2B41C4C95
PassNTLMv2      42E66127C6164E1C77B5F625D7DA2F6D    # Only for user 'millrt9', domain 'apac'
Username        millrt9
Domain          apac

# List of parent proxies to use. More proxies can be defined
# one per line in format <proxy_ip>:<proxy_port>
Proxy		proxy-per.bhpbilliton.net:8080
Proxy		proxy-per.bhpbilliton.net:8081
Proxy		proxy-bne.bhpbilliton.net:8080
Proxy		proxy-bne.bhpbilliton.net:8081

# List addresses you do not want to pass to parent proxies
# * and ? wildcards can be used
#
NoProxy		localhost, 127.0.0.*, 10.*, 192.168.*

# Specify the port cntlm will listen on
# You can bind cntlm to specific interface by specifying
# the appropriate IP address also in format <local_ip>:<local_port>
# Cntlm listens on 127.0.0.1:3128 by default
#
Listen		3128

# Enable to allow access from other computers
#Gateway	yes
